#!/usr/bin/env bash

## git configuration
git config --global push.autoSetupRemote true

#@--------------------------------@#
# Check if homebrew is installed
#@--------------------------------@#
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

if ! command -v brew &> /dev/null
then
    echo "Homebrew could not be found. Skipping..."
else
    echo "Installing fzf, bat, tree, jq, mycli, helm"
    HOMEBREW_NO_AUTO_UPDATE=1 brew install fzf bat tree jq mycli helm

    #@--------------------------------@#
    # Configure fzf
    #   - Install keybindings
    #   - Install shell completion
    #   - Do not update shell configuration files
    #@--------------------------------@#
    echo "Configuring fzf keybindings and shell completion"
    "$(brew --prefix)"/opt/fzf/install --key-bindings --completion
fi


#@--------------------------------@#
# Install vim pathogen
#@--------------------------------@#
echo "Installing vim pathogen"
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

echo "Installing apprentice theme"
git clone https://github.com/romainl/Apprentice.git ~/.vim/bundle/apprentice

#@--------------------------------@#
# Codespaces specific
#@--------------------------------@#
echo "Updating PATH for zsh"
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.zshrc
echo "PATH=$PATH:$(brew --prefix)/bin:/home/vscode/.local/bin" >> ~/.zshrc
echo "alias k=kubectl" >> ~/.zshrc
# Set theme
echo "Switching theme to minimal"
omz theme use minimal || true
# Kubectl completions
kubectl completion zsh > "${fpath[1]}/_kubectl" || true
# Helm completions
helm completion zsh > "${fpath[1]}/_helm" || true
