command_timeout = 500
scan_timeout = 10

[character]
success_symbol = "[➜](bold green)"
error_symbol = " [λ](bold red)"

[aws]
disabled=true

[cmd_duration]
format = ""

[time]
disabled = true
time_format = "%T"
format = "[$time]($style)"
utc_time_offset = "+1"

[git_branch]
symbol = "🌱 "

[git_commit]
commit_hash_length = 5
tag_symbol = "🔖 "

[git_status]
conflicted = "🏳"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[python]
pyenv_version_name=false

[container]
format = "[$symbol \\[$name\\]]($style) "
